- name: Install awscli
  apt:
    name: awscli

- name: Download awslogs agent
  shell:  curl https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb -O

- name: Install CWAgent
  shell:  sudo dpkg -i -E ./amazon-cloudwatch-agent.deb

- name: Copy AWS cloudwatch agent conf file 
  copy:
    src: files/config.json
    dest: /home/ubuntu/config.json

- name: Fix missing directory
  shell:  mkdir -p /usr/share/collectd/

- name: Fix missing files
  shell:  touch /usr/share/collectd/types.db

- name: Start Cloud Watch Agent
  shell:  sudo /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s -c file:/home/ubuntu/config.json
