- name: deploy web app
  command: chdir=/var/www/html git pull

- name: Install mb-sting
  shell:
    cmd: apt install php-mbstring -y

- name: Change wordpress OWner
  shell:
    cmd: chown -R www-data:www-data /var/www/html

- name: Stop Apache
  service: name=apache2 state=stopped enabled=yes

- name: Start Apache
  service: name=apache2 state=started enabled=yes
