- name: Update the apt-get cache
  apt:
    update_cache: yes

- name: Install PHP & dependencies
  apt:
    name: php

- name: Install PHP Mysql
  apt:
    name: php-mysql

- name: Install PHP Curl
  apt:
    name: php-curl

- name: Delete apache default index.html
  shell:
    cmd: rm -rf /var/www/html/index.html

- name: Download Wordpress
  get_url:
    url: https://fr.wordpress.org/latest-fr_FR.tar.gz
    dest: /home/ubuntu

- name: Unzip Wordpress
  shell:
    cmd: tar -xzvf /home/ubuntu/wordpress-*

- name: Clear
  shell:
    cmd: rm -rf /var/www/html/*

- name: Create health check
  shell:
    cmd: echo "i'm fine" > /var/www/html/health.html

- name: Copy wordpress to the apache directory /var/www/html
  shell:
    cmd: cp -a /home/ubuntu/wordpress/* /var/www/html

- name: Init Wordpres DB
  shell:
    cmd: cp /var/www/html/wp-config-sample.php /var/www/html/wp-config.php
    cmd: sed "s/^define( 'DB_NAME'.*/define( 'DB_NAME', 'webapp' );/g" /var/www/html/wp-config.php > /var/www/html/wp-config-1.php
    cmd: sed "s/^define( 'DB_NAME'.*/define( 'DB_USER', 'admin' );/g" /var/www/html/wp-config-1.php > /var/www/html/wp-config-2.php
    cmd: sed "s/^define( 'DB_PASSWORD'.*/define( 'DB_PASSWORD', 'admin2020' );/g" /var/www/html/wp-config-2.php > /var/www/html/wp-config-3.php
    cmd: sed "s/^define( 'DB_HOST'.*/define( 'DB_HOST', 'terraform-20201118082208541400000001.c3u6v41x0ahn.eu-west-1.rds.amazonaws.com' );/g" /var/www/html/wp-config-3.php > /var/www/html/wp-config-4.php
    cmd: rm wp-config.php
    cmd: mv wp-config-4.php wp-config.php
    

- name: Change wordpress OWner
  shell:
    cmd: chown -R www-data:www-data /var/www/html

- name: Stop Apache
  service: name=apache2 state=stopped enabled=yes

- name: Start Apache
  service: name=apache2 state=started enabled=yes
